version: '3.9'
services:
 db:
  image: mysql
  container_name: series-mysql
  environment:
   - MYSQL_DATABASE=series
   - MYSQL_ROOT_PASSWORD=123
  ports:
  - '3306:3306'
  volumes:
  - ./mysql-volume:/var/lib/mysql
  networks:
  - db
volumes:
 mysql-volume:
  driver: local
networks:
 db:
  driver: bridge