spring:
 application:
  name: series
 datasource:
  url: jdbc:mysql://localhost:3306/{database}?useTimezone=true&serverTimezone=America/Bahia
  username:  username
  password: passowrd
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect	
  hibernate:
   ddl-auto: update 
application:
 imdb:
  keys: api_key 
  url: https://www.omdbapi.com/